#spring:
# datasource:
#   url: jdbc:postgresql://db:5432/dbname
#   username: user
#   password: password
#   driver-class-name: org.postgresql.Driver
#   hikari:
#     maximum-pool-size: 5
#     minimum-idle: 1
#     idle-timeout: 10000
#     max-lifetime: 30000
#
# jpa:
#   hibernate:
#     ddl-auto: validate
#   show-sql: false
#   open-in-view: false
#
# flyway:
#   enabled: true
#   locations: classpath:db/migration
#   baseline-on-migrate: true
#
# mail:
#   host: smtp.gmail.com
#   port: 587
#   username: marcellapearl0627@gmail.com
#   password: iojqyfqewabuvtnd
#
# data:
#   redis:
#     url: redis://redis:6379
#     timeout: 5000ms
#     lettuce:
#       pool:
#         max-active: 20
#         max-idle: 10
#         min-idle: 2
#         max-wait: 2000ms
#
# kafka:
#   bootstrap-servers: kafka:29092
#
#   producer:
#     key-serializer: org.apache.kafka.common.serialization.StringSerializer
#     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#     acks: 1
#     retries: 3
#     properties:
#       spring.json.add.type.headers: false
#       max.request.size: 1048576
#
#   consumer:
#     group-id: workflow-coordinator
#     auto-offset-reset: earliest
#     key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#     value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#     properties:
#       spring.json.trusted.packages: '*'
#       spring.json.use.type.headers: false
#       spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#       spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#
# jackson:
#   serialization:
#     write-dates-as-timestamps: false
#   deserialization:
#     fail-on-unknown-properties: false
#
#jwt:
# secret: my-super-secret-jwt-key-1234567890
# expiration: 604800000
#
#server:
# port: 2706
# servlet:
#   context-path: /
# tomcat:
#   max-threads: 200
#   min-spare-threads: 10
#
#app:
# mail:
#   from: marcellapearl0627@gmail.com
#
#logging:
# level:
#   com.marcella.backend: INFO
#   org.springframework.kafka: WARN
#   org.apache.kafka: WARN
#   redis: WARN
#   org.springframework.web: INFO
# pattern:
#   console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#   file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#
#management:
# endpoints:
#   web:
#     exposure:
#       include: health,info,metrics
# endpoint:
#   health:
#     show-details: when-authorized
# health:
#   redis:
#     enabled: true
#   kafka:
#     enabled: true